# Generated by Django 6.0.6 on 2026-07-16 16:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['module', 'name'],
                'indexes': [models.Index(fields=['module'], name='permissions_module_2c0512_idx'), models.Index(fields=['code'], name='permissions_code_a0a529_idx')],
            },
        ),
    ]
