# Generated by Django 6.0.6 on 2026-07-12 11:02

import apps.organizations.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('branch_type', models.CharField(choices=[('HEADQUARTERS', 'Headquarters'), ('REGIONAL', 'Regional Office'), ('SITE', 'Site Office'), ('WAREHOUSE', 'Warehouse')], default='REGIONAL', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.organizations.models.branch_logo_upload_path)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('local_level', models.CharField(max_length=150)),
                ('local_level_type', models.CharField(max_length=50)),
                ('ward', models.PositiveSmallIntegerField()),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organizations.organization')),
            ],
            options={
                'db_table': 'branches',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization'], name='branches_organiz_c56918_idx'), models.Index(fields=['code'], name='branches_code_95622b_idx'), models.Index(fields=['branch_type'], name='branches_branch__e2680d_idx'), models.Index(fields=['is_active'], name='branches_is_acti_830392_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_branch_name_per_organization')],
            },
        ),
    ]
