# Generated by Django 6.0.6 on 2026-07-12 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.organization')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization'], name='roles_organiz_96c15d_idx'), models.Index(fields=['name'], name='roles_name_a96913_idx'), models.Index(fields=['is_active'], name='roles_is_acti_723ee4_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_role_per_organization')],
            },
        ),
    ]
