# Generated by Django 6.0.6 on 2026-07-14 18:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='organizations.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_members',
                'ordering': ['user__first_name', 'user__last_name'],
                'indexes': [models.Index(fields=['organization'], name='organizatio_organiz_a66366_idx'), models.Index(fields=['user'], name='organizatio_user_id_1a6a95_idx'), models.Index(fields=['role'], name='organizatio_role_id_e2fe49_idx'), models.Index(fields=['branch'], name='organizatio_branch__d9d4c9_idx'), models.Index(fields=['is_active'], name='organizatio_is_acti_14d01b_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='unique_user_per_organization')],
            },
        ),
    ]
